name: i18n_translated_text
description: A helper package for translating i18n:// prefixed texts. Uses flutter_i18n internally for translations.
version: 1.0.1

repository: https://github.com/nmshd/i18n_translated_text
homepage: https://enmeshed.eu

environment:
  sdk: "^3.2.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_i18n: ^0.35.1

dev_dependencies:
  flutter_lints: ^3.0.1
